// <auto-generated />
using System;
using GestionHuacales.Api9.DATA;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionHuacales.Api9.Migrations
{
    [DbContext(typeof(Contexto))]
    partial class ContextoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("GestionHuacales.Api9.Models.EntradasHuacales", b =>
                {
                    b.Property<int>("IdEntrada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.HasKey("IdEntrada");

                    b.ToTable("EntradasHuacales");
                });

            modelBuilder.Entity("GestionHuacales.Api9.Models.EntradasHuacalesDetalle", b =>
                {
                    b.Property<int>("DetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cantidad")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdEntrada")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Precio")
                        .HasColumnType("REAL");

                    b.Property<int>("TipoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("DetalleId");

                    b.HasIndex("IdEntrada");

                    b.HasIndex("TipoId");

                    b.ToTable("EntradasHuacalesDetalle");
                });

            modelBuilder.Entity("GestionHuacales.Api9.Models.TiposHuacales", b =>
                {
                    b.Property<int>("TipoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Existencia")
                        .HasColumnType("INTEGER");

                    b.HasKey("TipoId");

                    b.ToTable("TiposHuacales");

                    b.HasData(
                        new
                        {
                            TipoId = 1,
                            Descripcion = "Verde",
                            Existencia = 0
                        },
                        new
                        {
                            TipoId = 2,
                            Descripcion = "Rojo",
                            Existencia = 0
                        });
                });

            modelBuilder.Entity("GestionHuacales.Api9.Models.EntradasHuacalesDetalle", b =>
                {
                    b.HasOne("GestionHuacales.Api9.Models.EntradasHuacales", "EntradaHuacal")
                        .WithMany("EntradaHuacalDetalle")
                        .HasForeignKey("IdEntrada")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionHuacales.Api9.Models.TiposHuacales", "TipoHuacal")
                        .WithMany("EntradaHuacalDetalle")
                        .HasForeignKey("TipoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EntradaHuacal");

                    b.Navigation("TipoHuacal");
                });

            modelBuilder.Entity("GestionHuacales.Api9.Models.EntradasHuacales", b =>
                {
                    b.Navigation("EntradaHuacalDetalle");
                });

            modelBuilder.Entity("GestionHuacales.Api9.Models.TiposHuacales", b =>
                {
                    b.Navigation("EntradaHuacalDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
